version: 1

jobs:
  build:
    steps:
      - name: Init
        run: tofu init

      - name: Validate
        run: tofu validate

      - name: Plan
        run: tofu plan -out=tfplan

      - name: Apply
        if: $BRANCH == "main" && $MANUAL_APPROVED == "true"
        run: tofu apply tfplan

workflows:
  default:
    jobs:
      - build