version: 2.1

jobs:
  terraform-plan:
    docker:
      - image: hashicorp/terraform:1.6.6
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Debug Azure Env Vars
          command: |
            echo "ARM_CLIENT_ID: ${ARM_CLIENT_ID}"
            echo "ARM_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID}"
            echo "ARM_TENANT_ID: ${ARM_TENANT_ID}"
            echo "ARM_CLIENT_SECRET length: ${#ARM_CLIENT_SECRET}"
            env

      - run:
          name: Terraform Init
          command: terraform init

      - run:
          name: Terraform Validate
          command: terraform validate

      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan

      - persist_to_workspace:
          root: .
          paths:
            - tfplan

  terraform-apply:
    docker:
      - image: hashicorp/terraform:1.6.6
    working_directory: ~/project
    steps:
      - checkout

      - attach_workspace:
          at: .

      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve tfplan

workflows:
  version: 2

  terraform-deploy:
    jobs:
      - terraform-plan
      - hold-for-approval:
          type: approval
          requires:
            - terraform-plan
      - terraform-apply:
          requires:
            - hold-for-approval