version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0

jobs:
  apply_terraform:
    executor: terraform/default
    steps:
      - checkout

      - terraform/init:
          path: .

      - terraform/plan:
          path: .
          out: plan.tfplan

      - terraform/apply:
          path: .
          plan: plan.tfplan

workflows:
  terraform_workflow:
    jobs:
      - apply_terraform