version: 1

stages:
  - name: init
    commands:
      - tofu init

  - name: validate
    commands:
      - tofu validate

  - name: plan
    commands:
      - tofu plan -out=tfplan

  - name: apply
    when:
      branch: main
      manual: true
    commands:
      - tofu apply tfplan