version: 2.1

jobs:
  terraform:
    docker:
      - image: hashicorp/terraform:1.6.6  # Use official Terraform image
    working_directory: ~/project
    steps:
      - checkout

      # Debug step to check environment variables
      - run:
          name: Debug Azure Env Vars
          command: |
            echo "ARM_CLIENT_ID: ${ARM_CLIENT_ID}"
            echo "ARM_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID}"
            echo "ARM_TENANT_ID: ${ARM_TENANT_ID}"
            echo "ARM_CLIENT_SECRET length: ${#ARM_CLIENT_SECRET}"  # Check if it's set (without exposing the value)
            env  # List all environment variables (useful for debugging)

      - run:
          name: Terraform Init
          command: terraform init

      - run:
          name: Terraform Validate
          command: terraform validate

      - run:
          name: Terraform Plan
          command: terraform plan

workflows:
  version: 2
  terraform-deploy:
    jobs:
      - terraform