version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0

jobs:
  terraform-apply:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - terraform/init:
          path: .

      - terraform/plan:
          path: .
          out: plan.tfplan

      - terraform/apply:
          path: .
          plan: plan.tfplan
          auto-approve: true

workflows:
  terraform-deploy:
    jobs:
      - terraform-apply